ALTER TABLE health_checks ADD COLUMN dns_ok INTEGER NOT NULL DEFAULT 0;
ALTER TABLE health_checks ADD COLUMN ssh_ok INTEGER NOT NULL DEFAULT 0;
ALTER TABLE health_checks ADD COLUMN link_ok INTEGER NOT NULL DEFAULT 0;
